#!/bin/bash
# SimLingo Quick Start Script
# This script helps you quickly set up the SimLingo environment

set -e  # Exit on error

echo "========================================="
echo "SimLingo Quick Start Setup"
echo "========================================="
echo ""

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored messages
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on Linux
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    print_error "This script is designed for Linux systems"
    exit 1
fi

# Get user input for paths
print_info "Please provide the following information:"
echo ""

read -p "CARLA installation directory (default: ~/software/carla0915): " CARLA_ROOT
CARLA_ROOT=${CARLA_ROOT:-~/software/carla0915}
CARLA_ROOT=$(eval echo $CARLA_ROOT)  # Expand ~

read -p "SimLingo repository directory (default: ~/simlingo): " WORK_DIR
WORK_DIR=${WORK_DIR:-~/simlingo}
WORK_DIR=$(eval echo $WORK_DIR)  # Expand ~

read -p "Conda environment name (default: simlingo): " CONDA_ENV
CONDA_ENV=${CONDA_ENV:-simlingo}

echo ""
print_info "Configuration:"
echo "  CARLA_ROOT: $CARLA_ROOT"
echo "  WORK_DIR: $WORK_DIR"
echo "  CONDA_ENV: $CONDA_ENV"
echo ""

read -p "Continue with this configuration? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_info "Setup cancelled"
    exit 0
fi

# Step 1: Check CARLA installation
echo ""
print_info "Step 1/7: Checking CARLA installation..."

if [ ! -d "$CARLA_ROOT" ]; then
    print_warning "CARLA directory not found at $CARLA_ROOT"
    read -p "Would you like to install CARLA 0.9.15? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        print_info "Installing CARLA 0.9.15..."
        mkdir -p "$CARLA_ROOT"
        cd "$CARLA_ROOT"
        wget https://carla-releases.s3.us-east-005.backblazeb2.com/Linux/CARLA_0.9.15.tar.gz
        tar -xzf CARLA_0.9.15.tar.gz
        rm CARLA_0.9.15.tar.gz
        
        cd Import
        wget https://carla-releases.s3.us-east-005.backblazeb2.com/Linux/AdditionalMaps_0.9.15.tar.gz
        cd ..
        bash ImportAssets.sh
        
        print_info "CARLA installation complete!"
    else
        print_error "CARLA is required. Please install CARLA 0.9.15 manually."
        exit 1
    fi
else
    print_info "CARLA found at $CARLA_ROOT"
fi

# Step 2: Check repository
echo ""
print_info "Step 2/7: Checking repository..."

if [ ! -d "$WORK_DIR" ]; then
    print_error "SimLingo repository not found at $WORK_DIR"
    print_info "Please clone the repository first:"
    echo "  git clone https://github.com/zhangjenny/simlingo.git $WORK_DIR"
    exit 1
else
    print_info "Repository found at $WORK_DIR"
fi

cd "$WORK_DIR"

# Step 3: Check conda installation
echo ""
print_info "Step 3/7: Checking conda installation..."

if ! command -v conda &> /dev/null; then
    print_error "conda not found. Please install Anaconda or Miniconda first."
    exit 1
else
    print_info "conda found: $(conda --version)"
fi

# Step 4: Create or activate conda environment
echo ""
print_info "Step 4/7: Setting up conda environment..."

if conda env list | grep -q "^$CONDA_ENV "; then
    print_info "Conda environment '$CONDA_ENV' already exists"
    read -p "Would you like to recreate it? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        print_info "Removing existing environment..."
        conda env remove -n $CONDA_ENV -y
        print_info "Creating new environment..."
        conda env create -f environment.yaml -n $CONDA_ENV
    fi
else
    print_info "Creating conda environment '$CONDA_ENV'..."
    conda env create -f environment.yaml -n $CONDA_ENV
fi

# Step 5: Install PyTorch and flash-attn
echo ""
print_info "Step 5/7: Installing PyTorch and additional packages..."

# Activate environment
eval "$(conda shell.bash hook)"
conda activate $CONDA_ENV

print_info "Installing PyTorch 2.2.0..."
pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121

print_info "Installing flash-attn (this may take a while)..."
pip install flash-attn==2.7.0.post2 --no-build-isolation || {
    print_warning "flash-attn installation failed. Training will work but may be slower."
    print_warning "This is optional and can be skipped."
}

# Step 6: Create environment setup script
echo ""
print_info "Step 6/7: Creating environment setup script..."

cat > "$HOME/simlingo_env.sh" << EOF
#!/bin/bash
# SimLingo Environment Variables
# Generated by quick_start.sh

export CARLA_ROOT=$CARLA_ROOT
export WORK_DIR=$WORK_DIR
export PYTHONPATH=\$PYTHONPATH:\${CARLA_ROOT}/PythonAPI/carla
export PYTHONPATH=\$PYTHONPATH:\${CARLA_ROOT}/PythonAPI/carla/dist/carla-0.9.15-py3.8-linux-x86_64.egg
export PYTHONPATH=\$PYTHONPATH:\${WORK_DIR}
export SCENARIO_RUNNER_ROOT=\${WORK_DIR}/scenario_runner
export LEADERBOARD_ROOT=\${WORK_DIR}/leaderboard
export PYTHONPATH="\${CARLA_ROOT}/PythonAPI/carla/":\${SCENARIO_RUNNER_ROOT}:\${LEADERBOARD_ROOT}:\${PYTHONPATH}

# Optional: Uncomment for China users
# export HF_ENDPOINT=https://hf-mirror.com

echo "SimLingo environment variables configured"
echo "CARLA_ROOT: \$CARLA_ROOT"
echo "WORK_DIR: \$WORK_DIR"
EOF

chmod +x "$HOME/simlingo_env.sh"

print_info "Environment script created at $HOME/simlingo_env.sh"

# Step 7: Verify installation
echo ""
print_info "Step 7/7: Verifying installation..."

source "$HOME/simlingo_env.sh"

# Test PyTorch
print_info "Testing PyTorch..."
python -c "import torch; print(f'PyTorch version: {torch.__version__}'); print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA version: {torch.version.cuda if torch.cuda.is_available() else \"N/A\"}')" || {
    print_error "PyTorch test failed"
    exit 1
}

# Test CARLA
print_info "Testing CARLA Python API..."
python -c "import carla; print(f'CARLA version: {carla.__version__}')" || {
    print_error "CARLA Python API test failed"
    exit 1
}

# Summary
echo ""
echo "========================================="
print_info "Setup Complete!"
echo "========================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Activate the environment:"
echo "   conda activate $CONDA_ENV"
echo "   source ~/simlingo_env.sh"
echo ""
echo "2. Download the dataset (choose one):"
echo "   a) Mini dataset (4GB, for testing):"
echo "      bash download_mini.sh"
echo ""
echo "   b) Full dataset from HuggingFace:"
echo "      huggingface-cli download --repo-type dataset --resume-download RenzKa/simlingo --local-dir database/simlingo"
echo ""
echo "3. Test dataset loading:"
echo "   python test_dataset_loading.py"
echo ""
echo "4. Download pretrained model:"
echo "   mkdir -p checkpoints"
echo "   cd checkpoints"
echo "   git clone https://huggingface.co/RenzKa/simlingo"
echo ""
echo "5. Run evaluation or training:"
echo "   See REPRODUCTION_GUIDE.md or 复现步骤指南.md for details"
echo ""
print_info "For detailed instructions, see:"
echo "  - English: REPRODUCTION_GUIDE.md"
echo "  - Chinese: 复现步骤指南.md"
echo ""
print_info "Environment setup script saved at: ~/simlingo_env.sh"
print_info "Use 'source ~/simlingo_env.sh' before running SimLingo"
echo ""
